---
- name: Import Kibana GPG Key
  ansible.builtin.shell: "curl- fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"

- name: Add Kibana APT Repository
  ansible.builitn.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: "elastic-8.x.list"
- name: Install Kibana packages
  ansible.builtina.apt:
    name: Kibana
    state: present
  